apiVersion: apps/v1
kind: Deployment
metadata:
  name: amplitude-cohorts
  namespace: email
  labels:
    app: amplitude-cohorts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amplitude-cohorts
  template:
    metadata:
      labels:
        app: amplitude-cohorts
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: useinsider.com/worker-type
                    operator: In
                    values:
                      - spot
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - amplitude-cohorts
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 100
      containers:
        - name: amplitude-cohorts
          image: 936289044322.dkr.ecr.eu-west-1.amazonaws.com/contact-service/amplitude-cohorts:latest
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "250m"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 20"]
          readinessProbe:
            httpGet:
              port: 80
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: APP_PORT
              value: "80"
            - name: GIN_MODE
              value: "release"
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: email-service-secrets
                  key: CONTACT_SENTRY_DSN
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: publisher-secrets
                  key: MYSQL_HOST
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: publisher-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: publisher-secrets
                  key: MYSQL_PASS
---

apiVersion: v1
kind: Service
metadata:
  name: amplitude-cohorts
  namespace: email
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      targetPort: 80
      port: 80
  selector:
    app: amplitude-cohorts
